name: Playwright Tests

# Trigger the workflow on every push to any branch
on:
  push:
    branches:
      - '**'  # Run on every branch for every commit
  pull_request:
    branches:
      - '**'  # Run on every pull request for any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (adjust if you're using a different version)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies to speed up future builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Run Maven to execute Playwright tests
      - name: Run Playwright Tests
        run: |
          mvn verify
          mvn allure:report

      # Step 5: Upload the Allure results as an artifact for download
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results

      # Step 7: Publish Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin