name: Playwright Tests

# Trigger the workflow on every push to any branch
on:
  push:
    branches:
      - '**'  # Run on every branch for every commit
  pull_request:
    branches:
      - '**'  # Run on every pull request for any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (adjust if you're using a different version)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Install Maven 3.9.9
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.9

      # Step 4: Verify Maven installation
      - name: Verify Maven version
        run: mvn --version

      # Step 5: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 6: Install system dependencies for Playwright
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff1 \
            libopus0 \
            libwebp6 \
            libwebpdemux2 \
            libenchant1c2a \
            libgudev-1.0-0 \
            libsecret-1-0 \
            libhyphen0 \
            libgdk-pixbuf2.0-0 \
            libegl1 \
            libgles2 \
            libevent-2.1-7 \
            libnotify4 \
            libxslt1.1 \
            libxcomposite1 \
            libatk1.0-0 \
            libcups2 \
            libxrandr2 \
            libdbus-1-3 \
            libxtst6 \
            libnss3 \
            libasound2 \
            libxshmfence1

      # Step 6: Run Maven to execute Playwright tests
      - name: Run Playwright Tests
        run: mvn verify
